CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "Address" character varying(300) NOT NULL,
    "Contact" character varying(50) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Genres" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
);

CREATE TABLE "InboxState" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" uuid NOT NULL,
    "ConsumerId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Received" timestamp without time zone NOT NULL,
    "ReceiveCount" integer NOT NULL,
    "ExpirationTime" timestamp without time zone,
    "Consumed" timestamp without time zone,
    "Delivered" timestamp without time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
);

CREATE TABLE "Movies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Summary" character varying(2000) NOT NULL,
    "Year" integer NOT NULL,
    "Rating" numeric(3,1),
    "TrailerUrl" text NOT NULL,
    "PosterUrl" text NOT NULL,
    "MovieType" integer NOT NULL,
    CONSTRAINT "PK_Movies" PRIMARY KEY ("Id")
);

CREATE TABLE "OutboxState" (
    "OutboxId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Created" timestamp without time zone NOT NULL,
    "Delivered" timestamp without time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
);

CREATE TABLE "Persons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(200) NOT NULL,
    "Age" smallint NOT NULL,
    "PictureUrl" character varying(500) NOT NULL,
    CONSTRAINT "PK_Persons" PRIMARY KEY ("Id")
);

CREATE TABLE "Theaters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "NumOfRows" integer NOT NULL,
    "SeatsPerRow" integer NOT NULL,
    "Type" integer NOT NULL,
    CONSTRAINT "PK_Theaters" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MovieGenres" (
    "MovieId" integer NOT NULL,
    "GenreId" integer NOT NULL,
    CONSTRAINT "PK_MovieGenres" PRIMARY KEY ("MovieId", "GenreId"),
    CONSTRAINT "FK_MovieGenres_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES "Genres" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MovieGenres_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OutboxMessage" (
    "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EnqueueTime" timestamp without time zone,
    "SentTime" timestamp without time zone NOT NULL,
    "Headers" text,
    "Properties" text,
    "InboxMessageId" uuid,
    "InboxConsumerId" uuid,
    "OutboxId" uuid,
    "MessageId" uuid NOT NULL,
    "ContentType" character varying(256) NOT NULL,
    "MessageType" text NOT NULL,
    "Body" text NOT NULL,
    "ConversationId" uuid,
    "CorrelationId" uuid,
    "InitiatorId" uuid,
    "RequestId" uuid,
    "SourceAddress" character varying(256),
    "DestinationAddress" character varying(256),
    "ResponseAddress" character varying(256),
    "FaultAddress" character varying(256),
    "ExpirationTime" timestamp without time zone,
    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber"),
    CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId" FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES "InboxState" ("MessageId", "ConsumerId"),
    CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES "OutboxState" ("OutboxId")
);

CREATE TABLE "MoviePersons" (
    "MovieId" integer NOT NULL,
    "PersonId" integer NOT NULL,
    "RoleType" integer NOT NULL,
    CONSTRAINT "PK_MoviePersons" PRIMARY KEY ("MovieId", "PersonId", "RoleType"),
    CONSTRAINT "FK_MoviePersons_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MoviePersons_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Shows" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "MovieId" integer NOT NULL,
    "TheaterId" integer NOT NULL,
    "Status" integer NOT NULL,
    "Type" integer NOT NULL,
    CONSTRAINT "PK_Shows" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shows_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Shows_Theaters_TheaterId" FOREIGN KEY ("TheaterId") REFERENCES "Theaters" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TheaterSeats" (
    "SeatRow" character varying(5) NOT NULL,
    "SeatNumber" integer NOT NULL,
    "TheaterId" integer NOT NULL,
    "Type" integer NOT NULL,
    CONSTRAINT "PK_TheaterSeats" PRIMARY KEY ("TheaterId", "SeatRow", "SeatNumber"),
    CONSTRAINT "FK_TheaterSeats_Theaters_TheaterId" FOREIGN KEY ("TheaterId") REFERENCES "Theaters" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Bookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ShowId" integer NOT NULL,
    "SeatRow" character varying(5) NOT NULL,
    "SeatNumber" integer NOT NULL,
    "Price" real NOT NULL,
    "Status" integer NOT NULL,
    "BookingDateTime" timestamp without time zone NOT NULL,
    "ApplicationUserId" text,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_Bookings_Shows_ShowId" FOREIGN KEY ("ShowId") REFERENCES "Shows" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Amount" integer NOT NULL,
    "PaymentDateTime" timestamp without time zone NOT NULL,
    "Method" integer NOT NULL,
    "UserId" text NOT NULL,
    "ShowId" integer NOT NULL,
    "ApplicationUserId" text,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_Payments_Shows_ShowId" FOREIGN KEY ("ShowId") REFERENCES "Shows" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Bookings_ApplicationUserId" ON "Bookings" ("ApplicationUserId");

CREATE INDEX "IX_Bookings_ShowId" ON "Bookings" ("ShowId");

CREATE UNIQUE INDEX "IX_Genres_Name" ON "Genres" ("Name");

CREATE INDEX "IX_InboxState_Delivered" ON "InboxState" ("Delivered");

CREATE INDEX "IX_MovieGenres_GenreId" ON "MovieGenres" ("GenreId");

CREATE INDEX "IX_MoviePersons_PersonId" ON "MoviePersons" ("PersonId");

CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");

CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");

CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");

CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON "OutboxMessage" ("OutboxId", "SequenceNumber");

CREATE INDEX "IX_OutboxState_Created" ON "OutboxState" ("Created");

CREATE INDEX "IX_Payments_ApplicationUserId" ON "Payments" ("ApplicationUserId");

CREATE INDEX "IX_Payments_ShowId" ON "Payments" ("ShowId");

CREATE INDEX "IX_Shows_MovieId" ON "Shows" ("MovieId");

CREATE UNIQUE INDEX "IX_Shows_TheaterId_Date_StartTime" ON "Shows" ("TheaterId", "Date", "StartTime");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510085202_InitialCreate', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "AiAuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "Action" text NOT NULL,
    "Model" text,
    "PromptName" text,
    "RequestPayload" text,
    "ResponsePayload" text,
    "PromptTokens" integer,
    "CompletionTokens" integer,
    "LatencyMs" bigint NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_AiAuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "AiPrompts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Template" text NOT NULL,
    "Version" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Description" text,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_AiPrompts" PRIMARY KEY ("Id")
);

CREATE TABLE "AiSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text,
    "Model" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_AiSessions" PRIMARY KEY ("Id")
);

CREATE TABLE "AiMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SessionId" integer NOT NULL,
    "Role" text NOT NULL,
    "Content" text NOT NULL,
    "TokenCount" integer,
    "ToolCallId" text,
    "ToolName" text,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_AiMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AiMessages_AiSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "AiSessions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AiMessages_SessionId" ON "AiMessages" ("SessionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510091652_AddAiTables', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE "Movies" ADD "Embedding" vector(1024);

CREATE TABLE "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MovieId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Content" character varying(5000) NOT NULL,
    "Rating" integer NOT NULL,
    "Embedding" vector(1024),
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Movies_Embedding" ON "Movies" USING hnsw ("Embedding" vector_cosine_ops);

CREATE INDEX "IX_Reviews_Embedding" ON "Reviews" USING hnsw ("Embedding" vector_cosine_ops);

CREATE INDEX "IX_Reviews_MovieId" ON "Reviews" ("MovieId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510103046_AddPgVectorAndEmbeddings', '10.0.5');

COMMIT;

